# Generated by Django 4.0 on 2022-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('court_name', models.CharField(max_length=30)),
                ('sports_type', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=15)),
                ('booking_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('bg_image', models.ImageField(upload_to='background/')),
                ('first_image', models.ImageField(upload_to='turf/first')),
                ('second_image', models.ImageField(upload_to='turf/second')),
                ('third_image', models.ImageField(upload_to='turf/third')),
            ],
            options={
                'db_table': 'owners',
            },
        ),
    ]
