# Generated by Django 4.0 on 2022-03-22 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='status',
            field=models.CharField(default='requested', max_length=10),
        ),
        migrations.CreateModel(
            name='Slote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('slote', models.TimeField()),
                ('status', models.CharField(max_length=10)),
                ('turf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owners')),
            ],
            options={
                'db_table': 'slote',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('slote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.slote')),
                ('turf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owners')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
