# Generated by Django 4.0 on 2022-03-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='third_image',
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('bg_image', models.ImageField(upload_to='background/')),
                ('first_image', models.ImageField(upload_to='turf/')),
                ('second_image', models.ImageField(upload_to='turf/')),
                ('third_image', models.ImageField(upload_to='turf/')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owners')),
            ],
            options={
                'db_table': 'turf',
            },
        ),
    ]
