# Generated by Django 4.0 on 2022-03-31 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_remove_owners_bg_image_remove_owners_first_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='turf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.turf'),
        ),
        migrations.AlterField(
            model_name='slote',
            name='turf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.turf'),
        ),
    ]
