# Generated by Django 4.0 on 2022-04-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_booking_turf_id_alter_slote_turf_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slote_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.FloatField(default=0),
        ),
    ]
