# Generated by Django 4.0 on 2022-04-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_remove_slote_slote_booking_date_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
    ]
